name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node.js
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-dependencies
        run: npm install

      - name: Build app
        id: build-app
        run: npm run build

      - 